[project]
name = "function"
description = ""
version = "0.1.0"
requires-python = ">=3.9"
license = "MIT"
authors = [
  { name="Omar Assouma", email="omarassouma01@gmail.com"},
]
dependencies = [
  # Add your runtime dependencies here
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 120
skip-string-normalization = true
